### ISSUE TITLE
Improper handling of slash-escaped control characters

### ISSUE THREAD

**Issue by stockholmux** [lujiajing1126/redis-cli#12]
With this module:
`> set test "one\\ntwo"`
Yields (in real redis-cli monitor):
`"set" "test" "one\\\\ntwo"`

While real redis-cli with the same command:
`"set" "test" "one\\ntwo"`

**Comment by lujiajing1126** [comment]
I am not sure. But it seems that `node` automatically escape backslash `\`
to `\\` tacitly while reading from stdin, like the reverse of `util.inspect`
