### ISSUE TITLE
how can I use this cli tool to connect to a redis cluster

### ISSUE THREAD

**Issue by ruiqiliu** [lujiajing1126/redis-cli#27]
After I connected to a redis server, the rdcli always output this error:

`(error) MOVED 11911 100.85.13.159:6380`

How to fix this?

**Comment by lujiajing1126** [comment]
I suppose you are using redis cluster?

**Comment by lujiajing1126** [comment]
> After I connected to a redis server, the rdcli always output this error:
> 
> `(error) MOVED 11911 100.85.13.159:6380`
> 
> How to fix this?

Please try the latest version with

```shell
$ npm i -g redis-cli@next
```
