### ISSUE TITLE
Does not work with AWS Elasticache Redis

### ISSUE THREAD

**Issue by hanscrg** [lujiajing1126/redis-cli#32]
We tried redis-cli with AWS Elasticache Redis and it can make connection but sending command does not get response back. To produce the problem, 

first need to setup SSH tunnel to enable port forwarding, for example, use port 56379
Then run command 
rdcli -a [password] -p 56379 --tls

The redis-cli will shows prompt,
127.0.0.1:56379>

Starting from here, any command enter, there is no response back.

**Comment by lujiajing1126** [comment]
Thanks for reporting the problem!

I guess the problem is due to the `in-transit encryption` option which the program does not currently support.

I will have a check.

**Comment by joshuakeel** [comment]
Just wanted to say I also had issues with AWS ElastiCache, and would like to be able to use this module with it (with TLS).

**Comment by lujiajing1126** [comment]
@joshuakeel @hanscrg I've published a new version `v2.1.0` which supports `--tls` option now. I've tested with AWS ElasticCache equipped with `in-transit` encryption.

Pls have a try!

**Comment by lujiajing1126** [comment]
Pls reopen this if anything is wrong.

**Comment by joshuakeel** [comment]
@lujiajing1126 Seems to work now for me. Thanks a bunch!
