### ISSUE TITLE
Is there any way to execute rdcli with multiple command parameters?

### ISSUE THREAD

**Issue by joshuakeel** [lujiajing1126/redis-cli#34]
Hi there,

I'm trying to run multiple commands programmatically, but I'm having a hard time figuring out how to do this (if there is even a way). Basically I need to login to the Redis instance, then run multiple commands, but I need to do this programmatically. I'm trying to run this as a job from my CI/CD server, so I won't be there to type the commands into the REPL. :)

Here's an example of what I'd like to see:

`npx rdcli -h host -a password --tls ping ping`

This would run the Redis `ping` command twice.

Alternatively, I could read in the commands from a file:

`npx rdcli -h host -a password --tls < commands.txt`

Neither of these approaches work. Is there a way to accomplish what I want to do?

**Comment by lujiajing1126** [comment]
I prefer to support lua script.

Does Lua script meets your requirements?

**Comment by joshuakeel** [comment]
@lujiajing1126 I would imagine it would, but I'd have to know more to be sure. I want to ensure that Node.js and NPM packages are the only dependencies. In other words, I wouldn't want to have to also install a Lua interpreter. If Lua is just embedded in redis-cli, however, that should be fine, as long as I can use Lua to script out running multiple commands sequentially.

So I think the answer is yes, it does meet my requirements, as long as those things are true. Thanks for the speedy response! How long do you think it might take to implement Lua scripting? I'm wondering if I should look for an alternative interim solution.

**Comment by lujiajing1126** [comment]
> @lujiajing1126 I would imagine it would, but I'd have to know more to be sure. I want to ensure that Node.js and NPM packages are the only dependencies. In other words, I wouldn't want to have to also install a Lua interpreter. If Lua is just embedded in redis-cli, however, that should be fine, as long as I can use Lua to script out running multiple commands sequentially.
> 
> So I think the answer is yes, it does meet my requirements, as long as those things are true. Thanks for the speedy response! How long do you think it might take to implement Lua scripting? I'm wondering if I should look for an alternative interim solution.

As I understand, lua scripting does not rely on the client.

A possible workaround is 

```
$ npx redis-cli eval "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}" 2 key1 key2 first second
1) key1
2) key2
3) first
4) second
```

while the quoted string is the content of your lua script. With the help of `cat`, you can use the following command,

```
$ npx redis-cli eval "$(cat script.lua)" 2 key1 key2 first second
1) key1
2) key2
3) first
4) second
```

where you may put the script into a file.
