### ISSUE TITLE
Liberty Liberty Liberty issue

### ISSUE THREAD

**Issue by sorvis** [lujiajing1126/redis-cli#39]
Hello,

It appears that this package was vulnerable to the [liberty liberty liberty patch](https://github.com/aws/aws-cdk/issues/18323).
![image](https://user-images.githubusercontent.com/1037467/148827583-34b34994-822d-492b-8edf-adf7f99caf73.png)

Article here about it:
https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ 

Not sure if we need a PR in this repository to resolve the issue to pin a package dependency version?

**Comment by lujiajing1126** [comment]
@sorvis Thanks for your issue!

I've pinned `color.js` to exact 1.4.0 and just released a new version `2.1.2`. Would you please confirm this patch?

But it seems the problematic version has been removed from the npm registry.

https://www.npmjs.com/package/colors

**Comment by sorvis** [comment]
Working good now. Thank you for the help!
![image](https://user-images.githubusercontent.com/1037467/148944669-f34e31a5-d3e6-48e4-9cd5-9c4a9ac6c716.png)
