### ISSUE TITLE
release a new version on npm 

### ISSUE THREAD

**Issue by gkorland** [lujiajing1126/redis-cli#4]
the last version was released 3 years ago, is there any plan to release a new version?

**Comment by lujiajing1126** [comment]
Thanks for your PRs. 

I am busying with my paper last few days.
And I am now reviewing all your codes.
I would also make some upgrades and I hope I 
could publish a new version to `npm` before Christmas!

**Comment by gkorland** [comment]
Thanks!

**Comment by lujiajing1126** [comment]
Finally, I upload a new version `1.1.0`,
see `https://www.npmjs.com/package/redis-cli`

There is still some problem with `MONITOR` and `PUB/SUB`,
I will fix it in the next release.

Anyway, Thanks for your help and enjoy!
