### ISSUE TITLE
Implement -n arg to match native redis-cli option to use database number

### ISSUE THREAD

**Issue by coolkev** [lujiajing1126/redis-cli#46]
I need to be able to flush a specific database index from a non-interactive command line. The SELECT command works fine to select the correct database in interactive mode, but I can't run multiple commands in non-interactive mode. Adding the -n arg will solve this problem.

https://redis.io/docs/ui/cli/#host-port-password-and-database

**Comment by ithielnor** [comment]
This looks like exactly what I need, but the latest NPM package is 2.1.2. Can a new package be published containing this fix?
