### ISSUE TITLE
rdcli is not available?

### ISSUE THREAD

**Issue by datvm** [lujiajing1126/redis-cli#9]
I have installed Redis CLI with the instruction:

> npm install -g redis-cli

And it is installed successfully

> + redis-cli@1.1.0

But when running it, it shows an error

> PS C:\Users\name> rdcli
> The system cannot find the path specified.

Any change recently broke it or I am doing it wrong?

**Comment by lujiajing1126** [comment]
Yes. It's problem.
I write the bin file in `shell`, so it cannot run on` windows`.
For now, I may suggest you trying with `cygwin`.

I could change it to vanilla javascript soon.

**Comment by lujiajing1126** [comment]
I have published `1.1.1` to `npm`, pls have a try.
